baseURL = 'https://signalgone.github.io/b1/'
languageCode = 'en-us'
title = 'Signal Gone'
theme = 'PaperMod'
[params]
math = true
uglyURLs = true
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
 
[build]
  writeStats = true

[imaging]
resampleFilter = "box"
quality = 75