baseURL = 'https://signalgone.github.io/b1/'
languageCode = 'en-us'
title = 'Signal Gone'
theme = 'PaperMod'
staticDir = ['static']

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true

[params]
math = true



 
[build]
  writeStats = true

[imaging]
resampleFilter = "box"
quality = 75


