baseURL = 'https://signalgone.github.io/b1/'
languageCode = 'en-us'
title = 'Signal Gone'
theme = 'PaperMod'
staticDir = ['static']

ShowToc = true


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true

[params]
math = true
ShowReadingTime = true
ShowShareButtons = true
ShowBreadCrumbs = true

[params.homeInfoParams]
Title = "Welcome to my blog"
Content = "Modelling and Quantitative Finance."

#[[params.socialIcons]]
#name = "<platform>"
#url = "<link>"

#[[params.socialIcons]]
#name = "<platform 2>"
#url = "<link2>"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
identifier = "About me"
name = "About me"
url = "/about/"
weight = 10


[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20


[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 30
 
[build]
  writeStats = true

[imaging]
resampleFilter = "box"
quality = 75


