baseURL = 'https://signalgone.github.io/b1/'
languageCode = 'en-us'
title = 'Signal Gone'
theme = 'PaperMod'

[params]
math = true
uglyURLs = true

[imaging]
  [imaging.exif]
    disableDate = false
    disableLatLong = false
    excludeFields = ''
    includeFields = ''
