baseURL = 'https://signalgone.github.io/b1/'
languageCode = 'en-us'
title = 'Signal Gone'
theme = 'PaperMod'
staticDir = ['static']

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true

[params]
math = true

[params.homeInfoParams]
Title = "Welcome to my blog"
Content = "Modelling and Quantitative Finance."

#[[params.socialIcons]]
#name = "<platform>"
#url = "<link>"

#[[params.socialIcons]]
#name = "<platform 2>"
#url = "<link2>"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
identifier = "About me"
name = "About me"
url = "https://signalgone.github.io/b1/about/"
weight = 10


#[[menu.main]]
#identifier = "tags"
#name = "tags"
#url = "/tags/"
#weight = 20


 
[build]
  writeStats = true

[imaging]
resampleFilter = "box"
quality = 75


