name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.128.0/hugo_extended_0.128.0_linux-amd64.tar.gz'
          tar -C ${{ runner.temp }} -zxvf /tmp/hugo.tar.gz hugo
          mkdir built-site  # Create if not exist

      - name: Build
        run: ${{ runner.temp }}/hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git init
          git add .
          git commit -m "Updated site"
          git remote add origin https://github.com/yourusername/yourrepository.git
          git push --force --quiet origin gh-pages
