name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v4
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
        set -x  # Enable debug mode
        cp -R public/* ${GITHUB_WORKSPACE}/built-site/
        cd ${GITHUB_WORKSPACE}/built-site
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git status  # Check what changes are staged
        git commit -m 'Updated site' || echo "No changes to commit"
        git push || git push --force  # Try force push if normal push fails
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
